### ISSUE TITLE
Version Solving failed

### ISSUE THREAD

**Issue by abhay007kr** [lhamycodes/flutter_mapbox_autocomplete#3]
**After running flutter pub get:**

Because every version of flutter_mapbox_autocomplete depends on http ^0.12.0+2 and ridenow depends on http ^0.13.0, flutter_mapbox_autocomplete is forbidden.
So, because ridenow depends on flutter_mapbox_autocomplete ^1.0.4, version solving failed.
Running "flutter pub get" in ridenow...                                 
pub get failed (1; So, because ridenow depends on flutter_mapbox_autocomplete ^1.0.4, version solving failed.)

**Here is pubspec.yaml:**

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  The following adds the Cupertino Icons font to your application.
  Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_database: ^6.1.0
  fluttertoast: ^7.1.8
  progress_dialog: ^1.2.4
  google_maps_flutter: ^2.0.1
  geolocator: ^7.0.1
  http: ^0.13.0
  geocoder: ^0.2.1
  flutter_mapbox_autocomplete: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by psks1204** [comment]
Hi, @abhay007kr as the error was showing because of the deprecated HTTP package. I've updated the library and you can use this one if you still run into a problem let me know. [MapBox AutoComplete](https://pub.dev/packages/mapbox_autocomplete) try this one.

**Comment by lhamycodes** [comment]
fixed now
